### ISSUE TITLE
How to make custom images 

### ISSUE THREAD

**Issue by idtres** [bitluni/POVLightsaber#1]
I have the projecto working with the default settings/images
but I'm not getting how to use the tool to create the images.
Im geeting, a .h .txt and .json file from the app, but the code makes reference to .bin files.

Can you please specifiy how to upload custom files?
 
Amazin project btw ! :D

**Comment by bitluni** [comment]
Hey, sorry I had the wrong converter checked in...
check the new one under Converter/Converter.html
